src/main/java/com/lmax/disruptor/FatalExceptionHandler.java, src/main/java/com/lmax/disruptor/IgnoreExceptionHandler.java, src/main/java/com/lmax/disruptor/WorkProcessor.java, src/main/java/com/lmax/disruptor/WorkerPool.java, src/main/java/com/lmax/disruptor/dsl/ConsumerRepository.java, src/main/java/com/lmax/disruptor/dsl/Disruptor.java, src/main/java/com/lmax/disruptor/dsl/ExceptionHandlerSetting.java, src/test/java/com/lmax/disruptor/BatchEventProcessorTest.java, src/test/java/com/lmax/disruptor/FatalExceptionHandlerTest.java, src/test/java/com/lmax/disruptor/IgnoreExceptionHandlerTest.java, src/test/java/com/lmax/disruptor/dsl/stubs/StubExceptionHandler.java
We've pushed the generics for exception handler around a bit more so that the disruptor<T> and exceptionHandler<T> tie up. 
Things to look out for in your review:
- we've converted some usages of <?> to <T> 
- we've convinced ourselves that the cast in ExceptionHandlerSetting  with <T> will work out ok - but this bit felt a little dodgy.
=> More generics around usages of ExceptionHandler.java

src/perftest/java/com/lmax/disruptor/queue/OneToThreeDiamondQueueThroughputTest.java, src/perftest/java/com/lmax/disruptor/queue/OneToThreePipelineQueueThroughputTest.java, src/perftest/java/com/lmax/disruptor/queue/OneToThreeQueueThroughputTest.java, src/perftest/java/com/lmax/disruptor/queue/ThreeToOneQueueThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToThreeDiamondSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToThreePipelineSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToThreeSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/ThreeToOneSequencedBatchThroughputTest.java, src/perftest/java/com/lmax/disruptor/workhandler/OneToThreeReleasingWorkerPoolThroughputTest.java, src/perftest/java/com/lmax/disruptor/workhandler/OneToThreeWorkerPoolThroughputTest.java, src/perftest/java/com/lmax/disruptor/workhandler/TwoToTwoWorkProcessorThroughputTest.java
This is simple PR to add missing DaemonThreadFactory as parameter of executor to finish test case.
=> Add missing DaemonThreadFactory parameter to executor to finish test case

src/main/java/com/lmax/disruptor/dsl/Disruptor.java, src/main/java/com/lmax/disruptor/dsl/ExceptionHandlerWrapper.java, src/test/java/com/lmax/disruptor/DisruptorStressTest.java, src/test/java/com/lmax/disruptor/ShutdownOnFatalExceptionTest.java, src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java
…on handler for all event processors and worker pools created by Disruptor regardless of whether they were created before or after the call to setDefaultExceptionHandler. This fixes #122
=> Add Disruptor.setDefaultExceptionHandler API

src/main/java/com/lmax/disruptor/BlockingWaitStrategy.java, src/main/java/com/lmax/disruptor/LiteBlockingWaitStrategy.java, src/main/java/com/lmax/disruptor/TimeoutBlockingWaitStrategy.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - Dead stores should be removed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1854
Please let me know if you have any questions.
Kirill Vlasov
=> Dead stores should be removed

src/perftest/java/com/lmax/disruptor/support/MultiBufferBatchEventProcessor.java
There is a bug in `MultiBufferBatchEventProcessor`: when it reads a first available message in a ringbuffer it always set `endOfBatch` to false because `previous` would be -1 and `available` would be 0.
I've made a sample to illustrate this https://github.com/zergood/disruptor-sample
=> fix MultiBufferBatchEventProcessor endOfBatch handling bug

src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java
The BatchEventProcessor throws an exception as it has already been started.
=> Don't add processor twice

src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java
The test `shouldProcessMessagesPublishedBeforeStartIsCalled` is not testing anything because the initial `CountDownLatch` value is zero.
=> Fix initial CountDownLatch value in test

src/test/java/com/lmax/disruptor/RingBufferTest.java
There are a few tests in `RingBufferTest` that verify exceptions on both `publishEvents` and `tryPublishEvents` methods. Because the `publishEvents` methods throw the excepted exceptions, the `tryPublishEvents` are not tested.
=> Create separate tests for publishEvents and tryPublishEvents

runoffheap.sh, src/perftest/java/com/lmax/disruptor/offheap/OneToOneOffHeapThroughputTest.java, src/perftest/java/com/lmax/disruptor/offheap/OneToOneOnHeapThroughputTest.java
To better isolate the benefits of having a contiguos off heap ringbuffer directly referenced (ie `OneToOneOffHeapThroughputTest`) I've added the on heap case where the ring buffer slots are slices of the same contiguos buffer.
In addition I've used `ByteOrder::nativeOrder()` for all the buffers and `ByteBuffer::getLong(idx)`.
Now the differences (on my box at least) are very different from the original test!
=> Added sliced on heap ByteBuffer test

src/perftest/java/com/lmax/disruptor/AbstractPerfTestDisruptor.java, src/perftest/java/com/lmax/disruptor/PerfTestContext.java, src/perftest/java/com/lmax/disruptor/offheap/OneToOneOffHeapThroughputTest.java, src/perftest/java/com/lmax/disruptor/offheap/OneToOneOnHeapThroughputTest.java, src/perftest/java/com/lmax/disruptor/raw/OneToOneRawBatchThroughputTest.java, src/perftest/java/com/lmax/disruptor/raw/OneToOneRawThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToOneSequencedBatchThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToOneSequencedLongArrayThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToOneSequencedPollerThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToOneSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToThreeDiamondSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToThreePipelineSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/OneToThreeSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/ThreeToOneSequencedBatchThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/ThreeToOneSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/sequenced/ThreeToThreeSequencedThroughputTest.java, src/perftest/java/com/lmax/disruptor/support/LongArrayEventHandler.java, src/perftest/java/com/lmax/disruptor/support/ValueAdditionEventHandler.java, src/perftest/java/com/lmax/disruptor/support/ValueMutationEventHandler.java, src/perftest/java/com/lmax/disruptor/translator/OneToOneTranslatorThroughputTest.java, src/perftest/java/com/lmax/disruptor/workhandler/OneToThreeReleasingWorkerPoolThroughputTest.java, src/perftest/java/com/lmax/disruptor/workhandler/OneToThreeWorkerPoolThroughputTest.java, src/perftest/java/com/lmax/disruptor/workhandler/TwoToTwoWorkProcessorThroughputTest.java
We've recently added the batch percentage and average batch size to the disruptor-net performance tests.  We've found that it allows us to quickly see how the effects of batching impact the throughput figures.  I.e. the counter-intuitive effect that a slower consumer can lead to higher throughput as the rate of batching increases.
=> Add batch size to performance tests

src/main/java/com/lmax/disruptor/dsl/Disruptor.java, src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java
This is bugfix for DSL method Disruptor#after(EventProcessor...)
According the javadoc, event processors must previously be set up with handleEventsWith or some other method. However event processors passed as arguments will be added into consumerRepository, which leads to duplicate attempts to start processing threads.
New unittest provided is checking that number of times new threads started is the same as number of event processors/handlers.
=> Disruptor DSL - don't register processors in Disruptor#after(EventProcessor...)

src/main/java/com/lmax/disruptor/dsl/ConsumerRepository.java, src/main/java/com/lmax/disruptor/dsl/Disruptor.java
Stop doing unnecessary allocations in hasBacklog by delegating to ConsumerRepository rather than having ConsumerRepository pass back a Collection made of concatenated arrays.
=> Delegate hasBacklog to ConsumerRepository

src/perftest/java/com/lmax/disruptor/queue/ThreeToOneQueueBatchThroughputTest.java, src/perftest/java/com/lmax/disruptor/support/ValueAdditionQueueBatchProcessor.java
* Replace LinkedBlockingQueue with ArrayBlockingQueue as it's faster.
Benchmarks from my desktop (Linux, Intel® Core™ i7-6850K CPU @ 3.60GHz × 12)
```
Run 0, BlockingQueue=5,279,831 ops/sec
Run 1, BlockingQueue=4,595,588 ops/sec
Run 2, BlockingQueue=5,028,916 ops/sec
Run 3, BlockingQueue=5,606,952 ops/sec
Run 4, BlockingQueue=5,268,703 ops/sec
Run 5, BlockingQueue=5,054,334 ops/sec
Run 6, BlockingQueue=4,800,768 ops/sec
```
```
Run 0, BlockingQueue=3,757,279 ops/sec
Run 1, BlockingQueue=3,611,412 ops/sec
Run 2, BlockingQueue=3,725,088 ops/sec
Run 3, BlockingQueue=3,599,064 ops/sec
Run 4, BlockingQueue=3,591,309 ops/sec
Run 5, BlockingQueue=3,602,954 ops/sec
Run 6, BlockingQueue=3,692,762 ops/sec
```
```
Run 0, BlockingQueue=11,049,723 ops/sec
Run 1, BlockingQueue=11,514,104 ops/sec
Run 2, …
```
=> Add queue benchmark with batching

build.gradle
This is the first step in the process of modularizing the Disruptor JAR #234.
Adding Automatic-Module-Name in the manifest file makes the library usable as a Java automatic module without moving the library itself to Java 9 (or later) or creating a module-info.java.
This allows the Disruptor when loaded as an automatic module to get its name from the Automatic-Module-Name entry in MANIFEST.MF instead of being inferred from the filename. This second option is dangerous as filenames are far from being unique and stable.
This post explains the point of having an Automatic-Module-Name defined: http://branchandbound.net/blog/java/2017/12/automatic-module-name/
=> Add Automatic-Module-Name to MANIFEST.MF

src/main/java/com/lmax/disruptor/WorkProcessor.java, src/test/java/com/lmax/disruptor/RemoveWorkHandlerTest.java, src/test/java/com/lmax/disruptor/example/DynamicAddWorkHandler.java
https://github.com/LMAX-Exchange/disruptor/issues/286#issue-524274860
=> dynamic remove handler without message lost

build.gradle
There doesn't seem to be a true dependency on multi-thread to build.
=> allow builds with single thread

build.gradle, src/test/java/com/lmax/disruptor/IntermittentTests.java, src/test/java/com/lmax/disruptor/RemoveWorkHandlerTest.java, src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java
Add an `IntermittentTests` category and exclude tests categorised as such when running in CI until they get fixed.
Hopefully this should stop CI failing every other commit, but the tests are still fine to run locally rather than being ignored.
=> Exclude currently intermittent tests

build.gradle, src/docs/asciidoc/en/index.adoc
Three small changes:
1. Fix the latency histogram image on the main page
2. Stop generating JavaDoc under `/docs`, since we don't need to commit this manually any more
3. Replace the "Getting started" link on the index with the "User Guide"
=> Small improvements to the new document generation process

build.gradle, src/jmh/java/com/lmax/disruptor/BlockingQueueBenchmark.java, src/jmh/java/com/lmax/disruptor/SimpleBenchmark.java, src/jmh/java/com/lmax/disruptor/SingleProducerSingleConsumer.java, src/jmh/java/com/lmax/disruptor/util/Constants.java, src/jmh/java/com/lmax/disruptor/util/SimpleEvent.java, src/jmh/java/com/lmax/disruptor/util/SimpleEventHandler.java
All current performance tests appear to be written before JMH existed and relies on building a separate jar which gives results in a non-standard format.
We should use JMH and leverage the way it works and the profilers it comes with instead.
This is just testing the waters, converting `SimplePerformanceTest` only, before jumping in and writing more JMH benchmarks.
I am not well versed in writing JMH benchmarks so review welcome.
(Note: we can also pass the JMH run some JVM args to make it similar to `runme.sh`)
=> Add a JMH Benchmark

src/main/java/com/lmax/disruptor/WorkProcessor.java, src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java, src/test/java/com/lmax/disruptor/dsl/stubs/StubThreadFactory.java
As mentioned in #308 the WorkProcessor had a bug where if `halt` was called before the thread had begun executing, the WorkProcessor will set running to true and run forever (or until `halt` called again at least).
We have added a `RunState` enum with an `AtomicReference` so that if run is called after the state has moved to `HALTED` we do not run.
The two tests that were intermittent in `DisruptorTest` are no longer intermittent.
=> Fix intermittent tests in DisruptorTest

CHANGELOG.md, src/main/java/com/lmax/disruptor/RunState.java, src/main/java/com/lmax/disruptor/WorkProcessor.java, src/main/java/com/lmax/disruptor/WorkerPool.java, src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java, src/test/java/com/lmax/disruptor/dsl/stubs/StubThreadFactory.java
Our previous intermittency fix changed the meaning of `WorkProcessor::halt` and we should have updated the documentation to reflect that breaking change.
=> Retrospectively change the meaning of halt on WorkProcessor

build.gradle, src/test/java/com/lmax/disruptor/IntermittentTests.java
`WorkerPool` and friends used to be the source of intermittent unit tests due to race conditions.
Since we have removed these classes and their associated tests, I have not seen any intermittent test failures locally or in CI.
=> No more need for the IntermittentTests category

build.gradle, gradle/asciidoc.gradle, gradle/jmh.gradle, gradle/maven.gradle, gradle/perf.gradle
This is a follow-up to https://github.com/LMAX-Exchange/disruptor/pull/329 and contains all the changes in that PR plus some extra refactoring of the Gradle scripts.
I'm not sure if the suggested refactoring will be to everyone's tastes, so submitting these separately so it's slightly easier to review. If everyone is happy with the changes, they can either be incorporated into the above PR (if it is still waiting to be merged), or merged separately via this request.
There overall aim of this change is to tidy up, modernise and simplify the Gradle build script. 
The key changes are:
- replace the `java` plugin with `java-library`;
- replace the `maven` plugin with `maven-publish`;
- split (most) "non-core" build functionality (i.e. anything that isn't needed to just build the `.jar`) out …
=> Gradle refactoring

build.gradle
Currently, Gradle is attempting to run the `test` suite using the JUnit 4 platform; since everything was recently migrated to JUnit 5, none of the tests are found.
This PR fixes the problem :)
=> Tell Gradle to use the JUnit Platform runner

.github/workflows/jcstress-sanity.yml, .github/workflows/jcstress-stress.yml, .github/workflows/jcstress-weekly-stress.yml, build.gradle, gradle/jcstress.gradle, src/jcstress/java/com/lmax/disruptor/SequenceStress.java
`Sequence` is a very important class to the Disruptor and it has methods like `set` and `setVolatile` which do subtly different things. It also makes general promises for thread safety/atomicity.
Given Sequence has existed for quite some time, this is less of an exercise in testing and more one of documenting existing behaviour.
There are comments on the methods of `Sequence` explaining the Store/Store and Store/Load rules of some of the methods, hopefully this test backs up those comments with some examples.
With this in place the move away from `UNSAFE` to `VarHandle` will be a little more of a proven non-breaking change.
=> JCStress test for Sequence

src/jmh/java/com/lmax/disruptor/RingBufferFalseSharingBenchmark.java, src/main/java/com/lmax/disruptor/RingBuffer.java, src/main/java/com/lmax/disruptor/Sequence.java, src/main/java/com/lmax/disruptor/SingleProducerSequencer.java, src/test/java/com/lmax/disruptor/alternatives/SequenceUnsafe.java, src/test/java/com/lmax/disruptor/alternatives/SequenceVarHandle.java, src/test/java/com/lmax/disruptor/alternatives/SequenceVarHandleBarrier.java
To add to 4.0 work..
This is to make it work with JDK 15 memory layout changes.
see: https://shipilev.net/jvm/objects-inside-out/#_observation_hierarchy_tower_padding_trick_collapse_in_jdk_15
Should be harmless in earlier JDKs.
The changes save a bit of memory (up to 16 bytes on RingBuffer) by being able to fit bytes into internal JVM padding after object header etc. (You can see it with the JavaObjectLayout tool).
As far as false-sharing is concerned, I think that the Sequence changes are somewhat academic since we're trying to protect a single long from false-sharing and the new approach will not move it regardless. Still, it makes the code slightly less reliant on implementation quirks. 
With the ring buffer fields, this change will still prevent false sharing if the memory ordering …
=> Move false-sharing padding to be in bytes rather than longs

build.gradle, gradle/jmh.gradle, src/docs/asciidoc/en/user-guide/20_developing_the_disruptor.adoc, src/jcstress/java/com/lmax/disruptor/MultiProducerSequencerUnsafeStress.java, src/jcstress/java/com/lmax/disruptor/MultiProducerSequencerVarHandleStress.java, src/jmh/java/com/lmax/disruptor/MultiProducerSequencerBenchmark.java, src/jmh/java/com/lmax/disruptor/SequenceBenchmark.java, src/main/java/com/lmax/disruptor/MultiProducerSequencer.java, src/test/java/com/lmax/disruptor/alternatives/MultiProducerSequencerUnsafe.java, src/test/java/com/lmax/disruptor/alternatives/MultiProducerSequencerVarHandle.java
As part of moving towards JDK11 we should be removing uses of sun.misc.Unsafe
MultiProducerSequencer was using Unsafe to provide finer-grained concurrency controls around the availability array which we can replace with the newer VarHandle API.
While adding a JMH benchmark to try and compare the VarHandle version vs Unsafe I also took the opportunity to update the docs on how to run benchmarks on isolated CPUs.
I also changed gradle to use a plugin for JMH which let me build a single jar with all dependencies built in. This made shipping JMH jars to a test system easier when running the benchmarks in isolated mode.
The JCStress tests suggest that all concurrency promises from the unsafe version are still met.
The JMH benchmark results show that the code runs at the same speed, so changes …
=> Change MultiProducerSequencer to use VarHandle instead of Unsafe

src/jmh/java/com/lmax/disruptor/MultiProducerSingleConsumer.java, src/main/java/com/lmax/disruptor/MultiProducerSequencer.java, src/main/java/com/lmax/disruptor/Sequence.java, src/test/java/com/lmax/disruptor/RingBufferTest.java, src/test/java/com/lmax/disruptor/SequencerTest.java
The MultiProducerSequencer currently has contention problems when many threads try to get the next sequence. It is not necessary to loop trying to compareAndSet the new sequence number. The producer can allocate sequence numbers upfront as long as it does not return when the consumer has not consumed the slot yet. The up-front allocation is valid because the call to getHighestPublisedSequence is the one that will tell the consumer that a slot has been published by the publisher.
Note: this pull request was first issued as #355 (on the older version). This new pull request is based off the master branch. I've also added the MultiProducerSingleConsumer jmh benchmark test.
=> Increase MultiProducerSequencer performance on getting next sequence (master branch)

CHANGELOG.md, src/main/java/com/lmax/disruptor/FatalExceptionHandler.java, src/main/java/com/lmax/disruptor/IgnoreExceptionHandler.java
Changing from java.util.logging to the [Platform Logging API](https://openjdk.java.net/jeps/264) is preferable now that this library is targeting JDK 11.
* Removes the dependency on java.util.logging, which some modular applications may want to avoid.
* Both java.util.logging and System.Logger can be redirected to a logging framework of choice. However, doing so is far more clean, straightforward, and effective for System.Logger. (I would wager performant too, given jul's creation of LogRecord objects)
* By default, the System.Logger API routes to java.util.logging, so for the majority of users this will be a non-breaking change and the behavior will be exactly the same. It is listed as a breaking change because:
* FatalExceptionHandler's constructor taking a Logger has been removed.
* It …
=> Use platform logging API in FatalExceptionHandler and IgnoreExceptionHandler

src/jcstress/java/com/lmax/disruptor/LoggerInitializationStress.java, src/main/java/com/lmax/disruptor/BatchEventProcessor.java, src/main/java/com/lmax/disruptor/ExceptionHandlers.java, src/main/java/com/lmax/disruptor/dsl/ExceptionHandlerWrapper.java
Default java loggers are no longer initialized when custom
ExceptionHandler instances are provided. This allows logging
frameworks to delegate to disruptor without risking deadlocks.
Implementation notes:
This introduces a new public utility class `ExceptionHandlers` which exposes a singleton `ExceptionHandler<Object>` that can be lazily initialized. This allows the handler to be centrally controlled and shared between `BatchEventProcessor` and `ExceptionHandlerWrapper`.
The `ExceptionHandler` instances are stored in non-volatile fields, so I opted to null check and produce the default singleton instead of attempting to initialize the field to some default just prior to initialization. This way even unexpected concurrent initial accesses should not be able to produce different behavior if …
=> Fix #370: Logger instances are lazily initialized

src/main/java/com/lmax/disruptor/BatchEventProcessor.java, src/main/java/com/lmax/disruptor/ExceptionHandlers.java, src/main/java/com/lmax/disruptor/dsl/ExceptionHandlerWrapper.java
97f7973 is a clean cherry-pick, however the two ternary statements have been replaced with if/else in commit 
5bd1b48 due to the limitations of java 8 generic type inference.
I did not include aa24297 in this PR because the v3.4 branch does not use jcstress.
=> [3.4] Logger instances are lazily initialized 

.github/workflows/jcstress-quick.yml
I noticed that GHA workflow runs jcstress "sanity" mode as the commit-level check. "sanity" mode is really for jcstress infrastructure testing, as it spends almost no time in the tests themselves. If we want to run the fast testing that spend some time in test code, we are better off doing "quick" runs.
Downside: it takes about 7 minutes to run. This can be made better to culling the number of JVM configuration the tests run.
=> GHA: Perform "quick" jcstress run instead of "sanity"

build.gradle
The current URL (at github.com) only shows a 404 error.
While I was at it I switched the Apache Licence URL to HTTPS
=> Fix siteUrl

CHANGELOG.md, src/main/java/com/lmax/disruptor/EventPoller.java, src/main/java/com/lmax/disruptor/Sequencer.java
Documentation for EventPoller per #367 
While updating the changelog I noticed that all the changes are listed under "Breaking changes." Perhaps you would like to separate out the breaking changes from the others? You could use 3 categories for breaking changes, deprecations, and the rest.
=> Add javadocs to EventPoller and a related method

build.gradle, config/checkstyle/suppress.xml, gradle/asciidoc.gradle, src/docs/asciidoc/en/disruptor.adoc, src/docs/asciidoc/en/index.adoc, src/docs/asciidoc/en/user-guide/10_using_the_disruptor.adoc, src/docs/asciidoc/en/user-guide/20_design_and_implementation.adoc, src/docs/asciidoc/en/user-guide/30_known_issues.adoc, src/docs/asciidoc/en/user-guide/index.adoc, src/examples/java/com/lmax/disruptor/examples/EarlyReleaseHandler.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEvent.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEventFactory.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEventHandler.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEventProducer.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEventProducerWithTranslator.java, src/examples/java/com/lmax/disruptor/examples/longevent/lambdas/LongEventMain.java, src/examples/java/com/lmax/disruptor/examples/longevent/legacy/LongEventMain.java, src/examples/java/com/lmax/disruptor/examples/longevent/legacy/LongEventProducer.java, src/examples/java/com/lmax/disruptor/examples/longevent/methodrefs/LongEventMain.java, src/examples/java/com/lmax/disruptor/examples/objectevent/ClearingEventHandler.java, src/examples/java/com/lmax/disruptor/examples/objectevent/Main.java, src/examples/java/com/lmax/disruptor/examples/objectevent/ObjectEvent.java, src/examples/java/com/lmax/disruptor/examples/objectevent/ProcessingEventHandler.java
A PR for general improvements to the documentation.
So far:
- splitting out the examples so that we can prove they compile (spoilers: some previously didn't)
- highlighting important pieces of information using admonitions
- general rework of the "Using the Disruptor" section
=> General improvements to the documentation

src/jcstress/java/com/lmax/disruptor/LoggerInitializationStress.java, src/jmh/java/com/lmax/disruptor/ArrayAccessBenchmark.java, src/jmh/java/com/lmax/disruptor/RingBufferBenchmark.java, src/main/java/com/lmax/disruptor/util/Util.java, src/main/java/module-info.java, src/test/java/com/lmax/disruptor/alternatives/MultiProducerSequencerUnsafe.java, src/test/java/com/lmax/disruptor/alternatives/RingBufferArray.java, src/test/java/com/lmax/disruptor/alternatives/RingBufferUnsafe.java, src/test/java/com/lmax/disruptor/alternatives/SequenceDoublePadded.java, src/test/java/com/lmax/disruptor/alternatives/SequenceUnsafe.java, src/test/java/com/lmax/disruptor/util/UnsafeAccess.java
For #345 we aim to remove dependency on `sun.misc.Unsafe`
Change the RingBuffer to use a plain array access instead of using Unsafe, which appears to have been used in an attempt at speed gains only, no concurrency focus.
I have also added a start of a benchmark on array access to try standard, Unsafe, VarHandle, and MethodHandles to compare. It seems that standard array access is the winner.
As this was the last use of `Unsafe` in the main code, `Util::getUnsafe` could be removed from the main source and put in as a test util, given we still use `Unsafe` in tests (primarily for benchmarking and concurrency verification).
=> Remove use of Unsafe from Ringbuffer & Util

src/test/java/com/lmax/disruptor/BatchEventProcessorTest.java
The test setups a latch that is decremented on-event, and then waits on the latch before publishing any event.
Here, `latch.await(2, TimeUnit.SECONDS);` is just a complex equivalent to `Thread.sleep(2000)`, and it makes the test quite slow.
The behavior under test can be validated by increasing the sequencer number, which will unblock `SequenceBarrier.waitFor` in multi-producer mode, and then by waiting before publishing the sequence.
=> Fix shouldNotPassZeroSizeToBatchStartAware

src/examples/java/com/lmax/disruptor/examples/longevent/LongEventFactory.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEventHandler.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEventProducer.java, src/examples/java/com/lmax/disruptor/examples/longevent/LongEventProducerWithTranslator.java, src/examples/java/com/lmax/disruptor/examples/objectevent/ClearingEventHandler.java, src/main/java/com/lmax/disruptor/RingBuffer.java, src/test/java/com/lmax/disruptor/RewindBatchEventProcessorTest.java, src/test/java/com/lmax/disruptor/alternatives/RingBufferArray.java, src/test/java/com/lmax/disruptor/alternatives/RingBufferUnsafe.java, src/test/java/com/lmax/disruptor/dsl/stubs/StubExceptionHandler.java
I'm so sorry to delay raising a pull request for issue#405,cause i'm very busy a period ago.
I annotated some method overloads by @Override,it is necesseary for java project.
There are others like this：curly braces should follow the class name immediately, not on another line,etc.
Awaiting your review,thanks.
=> A PR for issue#405.

src/main/java/com/lmax/disruptor/SingleProducerSequencer.java, src/test/java/com/lmax/disruptor/SequencerTest.java
If a developer uses the wrong ProducerType, it's hard to detect.
This commit adds a check using assertions so a developer can fail in
test instead of being burnt in Production.
(There will be no runtime cost in Production.)
As can be seen from the commit, there was actually a test case that
started failing because a SingleProducerSequencer was accessed by two
threads...
=> Assert that only a single thread accesses a SingleProducerSequencer.

src/main/java/com/lmax/disruptor/RingBuffer.java
As mentioned issue 420:
1.RingBufferFields constructor method optimized
In RingBufferFields constructor metod:
`this.bufferSize = sequencer.getBufferSize();`
this line initialized the bufferSize field,so the next line
`this.entries = (E[]) new Object[sequencer.getBufferSize() + 2 * BUFFER_PAD];`
sequencer.getBufferSize() is not neccessaury for getting bufferSize,only from the bufferSize to initialing entries is well.
Cause sequencer.getBufferSize() method have one question:
In JVM, the sequencer's memory allocated in heap,each access sequencer require searching  heap,this progress is slowly compare to cache.
2.RingBuffer cache-line optimized
In the final class RingBuffer,the Disruptor defined a series of variables in the below:
`protected byte
p10, p11, p12, p13, p14, p15, p16, p17,
p20, …
=> A PR For issue #420

gradle/asciidoc.gradle, src/docs/asciidoc/en/disruptor.adoc, src/docs/asciidoc/en/index.adoc, src/docs/asciidoc/en/user-guide/10_using_the_disruptor.adoc, src/docs/asciidoc/en/user-guide/index.adoc
As per [eddieHRS](https://github.com/eddieHRS)'s comment, we can default the `imagesdir` property in the `.adoc` files to be IDEA friendly, and then override the value for this to something more appropriate for Gradle when building. This seems like it works for both situations.
Fixes #431
=> Make images work in both IDEA and Gradle

src/main/java/com/lmax/disruptor/BatchEventProcessor.java, src/main/java/com/lmax/disruptor/EventHandler.java, src/perftest/java/com/lmax/disruptor/offheap/OneToOneOffHeapThroughputTest.java, src/perftest/java/com/lmax/disruptor/offheap/OneToOneOnHeapThroughputTest.java, src/perftest/java/com/lmax/disruptor/support/LongArrayEventHandler.java, src/perftest/java/com/lmax/disruptor/support/ValueAdditionEventHandler.java, src/perftest/java/com/lmax/disruptor/support/ValueMutationEventHandler.java, src/test/java/com/lmax/disruptor/BatchEventProcessorTest.java, src/test/java/com/lmax/disruptor/MaxBatchSizeEventProcessorTest.java
Add an optional `maxBatchSize` parameter to `BatchEventProcessor`.
Defaults to `Integer.MAX_VALUE`.
Limits the amount of events that will be processed before updating the sequence in the `BatchEventProcessor`.
Closes #438
=> Add max batch size limit to BatchEventProcessor

src/main/java/com/lmax/disruptor/dsl/Disruptor.java
This change is a very minor cleanup.
The new code uses the expected helper to extract sequences from processors.
Also, the sequence array is now only created once and reused for `addGatingSequences` and `new EventHandlerGroup`, which should be safe because the `EventHandlerGroup` constructor makes defensive copies of input sequences.
=> Use Util.getSequencesFor to create sequences from processors

src/jmh/java/com/lmax/disruptor/MultiProducerSingleConsumer.java
Batch publication has much more complicated logic in the `MultiProducerSequencer` compared to the `SingleProducerSequencer` where the cursor is simply updated with the high sequence value.
Therefore, there is also room for optimizations! :-)
Specifically, I am working on an idea to use just a single bit per slot in the ring buffer to represent "publication status" rather than an `int` and it should have the same performance for single event publication but better performance for the batch publication case.
I've already seen great results with this approach in the Rust port I've written (https://github.com/nicholassm/disruptor-rs) and I would like to explore the same idea in the "original" Disruptor.
But first it would be nice with a JMH benchmark to actually measure things.
That's what …
=> Add JMH benchmark to measure multi-producer batch publication performance.

src/main/java/com/lmax/disruptor/EventHandlerBase.java
Disruptor uses java Lambdas pretty liberally in its documentation.  This is fine, but there's an annotation to designate this. 
While it's not strictly required, as Java will coerce even without it, a lack of the @FunctionalInterface makes it so Clojure cannot use its lambda syntax with Disruptor.  
Since I don't really see any reason *not* to have this annotation, I think it should be added.
=> Add @FunctionalInteface annotation for the eventhandlerbase
